### ISSUE TITLE
Tirar 404 cuando no encuentra algun recurso (por ejemplo salesorder)

### ISSUE THREAD

**Issue by juanmjacobs** [Parsimotion/producteca-sdk#22]
https://github.com/Parsimotion/producteca-sdk/blob/2f555a4e7816db234931924eff346353330e915d/src/salesOrdersApi.coffee#L42

Podría tirar un 404 para poder hacer algo como (por ejemplo en la channelSdk):

``` js
return this.salesOrderApi.getByIntegration(integration)
      .then(({ id }) => this.salesOrderApi.update(id, updatedSalesOrder))
      .catch(err => err.statusCode == 404, () => this.salesOrderApi.create(salesOrder));
```

**Comment by kevinszuchet** [comment]
Esto lo había subido yo, pero no vale la pena. La idea sería aprovechar que estamos usando una biblioteca en lugar de hacer una request a mano y olvidarnos de los status code de http tratando de usar excepciones. El tema con esto último es que tendriamos que importarnos la excepción en donde queramos usar la sdk para poder catchear la misma.
